name: Build and Deploy To Azure (Service Principal)

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: netsample1                             # set this to your application's name
  AZURE_WEBAPP_URL: 'https://netsample1.azurewebsites.net'  # set the application url
  AZURE_WEBAPP_PACKAGE_PATH: '.'                            # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x'                                      # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Deploy
    environment: dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master from Repository
      uses: actions/checkout@master
      
    - name: Login to Azure WebApp
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIAL_SP }}
        
    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Run npm install, build, and test
      run: |
        # Build and test the project
        npm install
        npm run compile --if-present
        npm run build --if-present
        npm run test --if-present
      
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
    - name: Logout from Azure
      run: |
        az logout
    
    - name: Check the deployed Azure WebApp
      uses: jtalk/url-health-check-action@v2
      with:
        # Check the following URLs one by one sequentially
        url: ${{ env.AZURE_WEBAPP_URL }}
        # Follow redirects, or just report success on 3xx status codes
        follow-redirect: false # Optional, defaults to "false"
        # Fail this action after this many failed attempts
        max-attempts: 3 # Optional, defaults to 1
        # Delay between retries
        retry-delay: 5s # Optional, only applicable to max-attempts > 1
        # Retry all errors, including 404. This option might trigger curl upgrade.
        retry-all: false # Optional, defaults to "false"
